### PR TITLE
Update README.md

### LINKED ISSUE #146: [Bug] - Edit Hangar/src/slack/README.md to reflect the name change in Slack API.
### Pre-requisites:
- [X] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

## Description

[Slack App Setup](https://github.com/AmericanAirlines/Hangar/blob/main/src/slack/README.md#after-deploying-hangar) page needs update because Slack API page changed their wording on a specific tab. In order to reflect this change we need to change the wording under our README.md as well. 

## Expected Behavior

Change "Interactive Components" to "Interactivity & Shortcuts" under [After Deploying Hangar](https://github.com/AmericanAirlines/Hangar/blob/main/src/slack/README.md#after-deploying-hangar)

## Steps to Reproduce

Just change the name please.

### PR DESCRIPTION
**Pull request by oscargoddard**
## Pre-Requisites
- [X] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [X] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [X] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

made the required changes to README.md under Hangar/src/Slack

## Related Issues

Closes #146

### CODE REVIEW

**Review by SpencerKaiser — APPROVED** [review]
Looks great, but make sure to add the syntax to close the related issue when this is merged (e.g., `Closes #123`)

**Review by SpencerKaiser — APPROVED** [review]

**Review by SpencerKaiser — CHANGES_REQUESTED** [review]
@oscargoddard you checked this box but you aren't in that file on `main`:
> Yes, I updated Authors.md OR this is not my first contribution

Please add yourself to `Authors.md` and we can merge this

**Comment by oscargoddard** [comment]
> @oscargoddard you checked this box but you aren't in that file on `main`:
> 
> > Yes, I updated Authors.md OR this is not my first contribution
> 
> Please add yourself to `Authors.md` and we can merge this

Since this is the second pull request I made,  I thought we will already merge the one before this and I will not need to add it again. Sorry for that.

**Comment by SpencerKaiser** [comment]
@oscargoddard no worries. I made a comment on that one; there are a few more changes that need to be made before we can merge that one 🙂

**Comment by oscargoddard** [comment]
> @oscargoddard no worries. I made a comment on that one; there are a few more changes that need to be made before we can merge that one 🙂

I moved the text edited by you under # Local Development for the other pull request.

**Comment by SpencerKaiser** [comment]
@oscargoddard make sure to see my comment from above:
>Looks great, but make sure to add the syntax to close the related issue when this is merged (e.g., Closes #123)

**Comment by oscargoddard** [comment]
> @oscargoddard make sure to see my comment from above:
> 
> > Looks great, but make sure to add the syntax to close the related issue when this is merged (e.g., Closes #123)

I updated.

**Review by SpencerKaiser — APPROVED** [review]

**Pull request merged**
