### PR TITLE
Coming soon

### LINKED ISSUE #130: [Feature Request] - Move production docs to github pages
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.
For people not wanting to develop locally, there should be a github pages site that they can go to for setup instructions

## Describe the solution you'd like
Using a solution that keeps the docs as markdown in the repo would make it easier to link to it from the developer docs. A good one is [Docsify](https://docsify.js.org/#/).

## Describe alternatives you've considered
Not

## Additional context
https://docsify.js.org/#/

Original docs for setting up hangar without code: https://github.com/AmericanAirlines/Hangar/tree/7480526a3aee419d6bd7c417178aa833a9a5eecb

Dependent on #177

### LINKED ISSUE #177: [Feature Request] - Create new "Coming Soon" GitHub Pages site
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

We should create a new user-friendly docs site to help non-technical people get Hangar up and running (e.g., a non-customized version of Hangar without coding changes incorporated).

## Describe the solution you'd like

We should set up a "Coming Soon" pages site which has simple branding and a message saying the site contents are coming soon. We should utilize [Docsify](https://docsify.js.org/#/) for our docs site engine.

### PR DESCRIPTION
**Pull request by oscargoddard**
## Pre-Requisites
- [X] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [X] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [X] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

We created a Github coming soon page. 

We moved production docs to the github pages 

## Related Issues

Closes #177 
Closes #130 
We worked with @TheDivexz on this PR

### CODE REVIEW

**Comment by TheDivexz** [comment]
Screen Shot 2020-10-06 at 6 51 29 PM

This is what the site looks like right now

**Review by johnkahn — APPROVED** [review]
Looks good to me 👍

**Comment by SpencerKaiser** [comment]
One quick question... why is there a new `/docs/README.md` file? If that's being consumed from the site, can we move the original one here and only have one README? I just want to avoid having to maintain two separate but identical docs.

**Comment by TheDivexz** [comment]
You can set it to use the existing readme as well however, the initial pull request was for a separate coming soon page which is why we created a separate README

**Comment by johnkahn** [comment]
We'll want separate README files since one will be for developers and the other is for production setup 👍

**Pull request merged**
