### PR TITLE
UI component for editing config items

### LINKED ISSUE #204: [Feature Request] - UI Component for Editing Config Items
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

Currently there isn't an ability to change config items on the front-end side of things.

## Describe the solution you'd like

As it stands, the user has to go into the database in order to change the config items. We want to implement a way for the user to interact with and change these config items on a page.

## Describe alternatives you've considered

This implementation can be added in a few ways. One idea is to hook each config item to a button and have the button serve as a toggle (we will also have a clear way to show which toggle option it is set to). Another way is to have a drop-down menu for each config item. There are multiple ways we could do this, so these are simply idea pitches. Additionally, we need to figure out which page this should be added to (admin page? Its own page? etc.).

### PR DESCRIPTION
**Pull request by oscargoddard**
Co-Authored-By: Dhruv Tailor <11343998+TheDivexz@users.noreply.github.com>
Co-Authored-By: Joseph Nalepka <70769982+Peruggia29@users.noreply.github.com>

## Pre-Requisites
- [X] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [X] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [X] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

added the button
added the function to handletoogle

## Related Issues

closes #204

### CODE REVIEW

**Comment by oscargoddard** [comment]
My computer died and while I was trying to fix it all my branches are gone. Created another branch and another PR for this issue.

**Review by johnkahn — DISMISSED** [review]

**Review by SpencerKaiser — COMMENTED** [review]
I don't see a refresh or anything in here... do we need to add that?

**Comment by johnkahn** [comment]
This part handles that
https://github.com/AmericanAirlines/Hangar/pull/230/files#diff-18e0d4553c97cfc420e938ccafb4e3a688e782fa4512ba4ceae3e2a6f24c1987R84-R89

**Comment by SpencerKaiser** [comment]
@johnkahn but what if I have the page open and you change a value? It won't change for me unless I refresh the page and changing the value will "work" but the expected timing will be wrong.

**Comment by johnkahn** [comment]
Ah, I see what you mean

**Review by johnkahn — APPROVED** [review]

**Pull request merged**
