### PR TITLE
Page crash fix and README addition

### LINKED ISSUE #32: [Feature Request] - Add documentation for GitHub Secrets
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Describe the solution you'd like

This project utilizes GitHub secrets but there isn't a description of what secrets should be added or where to generate them. A section should be added to the README with suggested and required secrets and where to generate each.

As part of this issue, add a new section to the CI/CD part of the readme to document Codecov (do some research and set it up for your own fork of this project).

### PR DESCRIPTION
**Pull request by Ulfingrad**
## Pre-Requisites
- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevant code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

### CODE REVIEW

**Comment by Ulfingrad** [comment]
For some reason the change description and related issues were not included.

These changes fix the bug demonstrated to us in which the page will crash if "Get Next In Queue" is pressed when there are no support requests left. Additionally, README changes detailing GitHub secrets was added.

The related issues are #97 and #32

**Review by SpencerKaiser — CHANGES_REQUESTED** [review]
@Ulfingrad please break these changes into two separate PRs. Pull Requests should always target a single issue to keep them smaller and making them easier to review.

**Comment by SpencerKaiser** [comment]
@Ulfingrad you're welcome to take whatever approach you'd like, but you can absolutely leave this PR open and just revert the changes for one of the two items covered in this PR + change the description/title. Opening two new PRs is totally fine though.

**Comment by Ulfingrad** [comment]
@SpencerKaiser I'll probably just create 2 new ones this time around, but would you prefer it if I edited the already opened PR and create single new one in the future?

Also apologies for not splitting the two changes up at the very beginning.

**Pull request closed without merging**
