### PR TITLE
Home page

### LINKED ISSUE #384: Create nav bar and default pages
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Description

Create a nav bar and blank pages for the following:
- My Project - `/app/project` 
- Get Help - `/app/help` 
- Work at American - `/work-at-american`

The nav element should include an SVG for the Hangar logo using the [Hangar font](https://fonts.google.com/specimen/Pacifico?query=paci&preview.text=Hangar&preview.text_type=custom)
- John to make the SVG(s)

### LINKED ISSUE #394: Home Page
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Description

Hard code the Header and these sections:
- Challenge
- How to Win
- Resources

And then incorporate these components:
- Prizes (#389)
- Schedule (#387)

In the header section, include the following:
- Remind me component (#393)
- `Pre-Register` button which links to `/app/project` (#384)

### PR DESCRIPTION
**Pull request by johnkahn**
### Pre-Requisites

- [x] Yes, I updated [Authors.md](../blob/main/Authors.md) **OR** this is not my first contribution
- [x] Yes, I included and/or modified tests to cover relevant code **OR** my change is non-technical
- [x] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../blob/main/THIRD-PARTY-NOTICES.txt)

## Description of Changes

Created the home page with modified schedule and prizes components to fit in the smaller area

## Related Issues

Closes #384 
Closes #394 

## Video

https://user-images.githubusercontent.com/7807353/140800694-29008885-50ae-4f2a-b933-24bce06fcf4a.mov

### CODE REVIEW

**Review by Ulfingrad — APPROVED** [review]
Looks good to me, although it's a pretty large PR so I could've skimmed over something by accident. The only thing I saw was a missing newline at the end of `Logo.svg`, but idk if we care about that for svg files or not

**Review by dre8597 — COMMENTED** [review]
LGTM, once you add the colors for dark mode on the schedule component, we can ship it 🚀

**Comment by johnkahn** [comment]
> Looks good to me, although it's a pretty large PR so I could've skimmed over something by accident. The only thing I saw was a missing newline at the end of `Logo.svg`, but idk if we care about that for svg files or not

Yeah, for a logo we don't care

**Review by dre8597 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
